/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancesystem;

import java.awt.Color;
import java.awt.Cursor;


/**
 *
 * @author Hamza
 */
public class UIadmin extends javax.swing.JFrame {

    /**
     * Creates new form main_interface
     */
    public UIadmin() {
        initComponents();
        jLabel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        list1 = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblect = new javax.swing.JTable();
        jtxtsearch = new javax.swing.JTextField();
        jcbsearchuser = new javax.swing.JComboBox<>();
        jbtnsearch = new javax.swing.JButton();
        jbtnupdate = new javax.swing.JButton();
        jbtndelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnstumanage = new javax.swing.JButton();
        jbtnregistration = new javax.swing.JButton();
        jbtnlectmanage = new javax.swing.JButton();
        jbtnfeedback = new javax.swing.JButton();
        jbtnlogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Attendance Management System");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtblect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtblect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtblect.setGridColor(new java.awt.Color(255, 255, 255));
        jtblect.setNextFocusableComponent(this);
        jtblect.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jtblect.setSurrendersFocusOnKeystroke(true);
        jtblect.setVerifyInputWhenFocusTarget(false);
        jtblect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblectMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblect);

        jtxtsearch.setForeground(new java.awt.Color(153, 153, 153));
        jtxtsearch.setText("search id/name...");
        jtxtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtsearchMouseClicked(evt);
            }
        });
        jtxtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsearchActionPerformed(evt);
            }
        });

        jcbsearchuser.setBackground(new java.awt.Color(0, 153, 153));
        jcbsearchuser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jcbsearchuser.setForeground(new java.awt.Color(255, 255, 255));
        jcbsearchuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecturer", "Student" }));

        jbtnsearch.setBackground(new java.awt.Color(0, 153, 153));
        jbtnsearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jbtnsearch.setForeground(new java.awt.Color(255, 255, 255));
        jbtnsearch.setText("Search");
        jbtnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsearchActionPerformed(evt);
            }
        });

        jbtnupdate.setBackground(new java.awt.Color(0, 153, 153));
        jbtnupdate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtnupdate.setForeground(new java.awt.Color(255, 255, 255));
        jbtnupdate.setText("Update");
        jbtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupdateActionPerformed(evt);
            }
        });

        jbtndelete.setBackground(new java.awt.Color(0, 153, 153));
        jbtndelete.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtndelete.setForeground(new java.awt.Color(255, 255, 255));
        jbtndelete.setText("Delete");
        jbtndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeleteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(95, 67, 123));

        jbtnstumanage.setBackground(new java.awt.Color(153, 51, 255));
        jbtnstumanage.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnstumanage.setForeground(new java.awt.Color(255, 255, 255));
        jbtnstumanage.setText("Student Management");
        jbtnstumanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnstumanageActionPerformed(evt);
            }
        });

        jbtnregistration.setBackground(new java.awt.Color(153, 51, 255));
        jbtnregistration.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnregistration.setForeground(new java.awt.Color(255, 255, 255));
        jbtnregistration.setText("Registration");
        jbtnregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnregistrationActionPerformed(evt);
            }
        });

        jbtnlectmanage.setBackground(new java.awt.Color(153, 51, 255));
        jbtnlectmanage.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnlectmanage.setForeground(new java.awt.Color(255, 255, 255));
        jbtnlectmanage.setText("Lecturer Management");
        jbtnlectmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlectmanageActionPerformed(evt);
            }
        });

        jbtnfeedback.setBackground(new java.awt.Color(153, 51, 255));
        jbtnfeedback.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnfeedback.setForeground(new java.awt.Color(255, 255, 255));
        jbtnfeedback.setText("Student Feedback");
        jbtnfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnfeedbackActionPerformed(evt);
            }
        });

        jbtnlogout.setBackground(new java.awt.Color(153, 51, 255));
        jbtnlogout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnlogout.setForeground(new java.awt.Color(255, 255, 255));
        jbtnlogout.setText("Logout");
        jbtnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogoutActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancesystem/icon/9.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnstumanage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtnregistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtnlectmanage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtnfeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbtnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnregistration, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnstumanage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnlectmanage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel1.setText("Welcome to the  Attendance Management System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel3.setText("TO UPDATE OR DELETE PLEASE ENTER ID OR NAME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbsearchuser, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbsearchuser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1041, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnregistrationActionPerformed

         new UIreg().setVisible(true);    
    }//GEN-LAST:event_jbtnregistrationActionPerformed

    private void jbtnlectmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlectmanageActionPerformed
      jbtndelete.setVisible(false);
      jbtnupdate.setVisible(false);
      jLabel3.setVisible(true);
        Admin admin = new Admin();
        admin.viewlect();   
    }//GEN-LAST:event_jbtnlectmanageActionPerformed

    private void jbtnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsearchActionPerformed
       jbtndelete.setVisible(true);
       jbtnupdate.setVisible(true);
       jLabel3.setVisible(false);
       Admin admin = new Admin();
            if(jtxtsearch.getText().equals("search id/name...")||jtxtsearch.getText().equals(""))
            {
                    Popup p=new Popup();   
                    p.setlabel("PLEASE ENTER ID OR NAME TO SEARCH");
                    p.show();
            }
            else{switch((String)jcbsearchuser.getSelectedItem()){
            case "Lecturer": 
            admin.searchlect();
            break;
            case "Student":
            admin.searchstu();
            break;
            }}    
    }//GEN-LAST:event_jbtnsearchActionPerformed

    private void jbtnstumanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnstumanageActionPerformed
      jbtndelete.setVisible(false);
      jbtnupdate.setVisible(false);
      jLabel3.setVisible(true);
      Admin admin = new Admin();
      admin.viewstu();
    }//GEN-LAST:event_jbtnstumanageActionPerformed

    private void jbtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogoutActionPerformed
       Admin admin = new Admin();
       admin.logout();
       dispose();
    }//GEN-LAST:event_jbtnlogoutActionPerformed

    private void jbtnfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnfeedbackActionPerformed
      Admin admin = new Admin();
      admin.checkfeedback();       
    }//GEN-LAST:event_jbtnfeedbackActionPerformed

    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed
        
      
        
       
        Admin admin = new Admin();
            if(jtxtsearch.getText().equals("search id/name...")||jtxtsearch.getText().equals("")){
                    Popup p=new Popup();   
                    p.setlabel("NO RECORD FOUND TO UPDATE");
                    p.show();
            }else{
            switch((String)jcbsearchuser.getSelectedItem()){
            case "Lecturer": 
                admin.modifylect();
                break;
            case "Student":
                admin.modifystu();
               break;
       }}
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
        Admin admin = new Admin();
              if(jtxtsearch.getText().equals("search id/name...")||jtxtsearch.getText().equals("")){
                      Popup p=new Popup();   
                      p.setlabel("NO RECORD FOUND TO DELETE");
                      p.show();
              }else{
                switch ((String) jcbsearchuser.getSelectedItem()) {
                case "Lecturer":
                admin.deletelect();
                break;
                case "Student":
                admin.deletestu();
                break;
                }}
    }//GEN-LAST:event_jbtndeleteActionPerformed

    private void jtxtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsearchActionPerformed

    private void jtxtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtsearchMouseClicked
       jtxtsearch.setText("");
       jtxtsearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtxtsearchMouseClicked

    private void jtblectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblectMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtblectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIlogin().setVisible(true);
            }
        });
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JButton jbtnfeedback;
    private javax.swing.JButton jbtnlectmanage;
    private javax.swing.JButton jbtnlogout;
    private javax.swing.JButton jbtnregistration;
    private javax.swing.JButton jbtnsearch;
    private javax.swing.JButton jbtnstumanage;
    private javax.swing.JButton jbtnupdate;
    private javax.swing.JComboBox<String> jcbsearchuser;
    public static javax.swing.JTable jtblect;
    public static javax.swing.JTextField jtxtsearch;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
